name: Deploy to NCP

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: koliving_fe

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'bsideproject/KoLiving_FE'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image / tag with build number
        run: docker-compose build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          NCP_NCR: ${{ secrets.NCP_NCR }}
          IMAGE_NAME: koliving_fe

      - name: Build Docker image / tag latest
        run: docker-compose build
        env:
          BUILD_NUMBER: latest
          NCP_NCR: ${{ secrets.NCP_NCR }}
          IMAGE_NAME: $IMAGE_NAME

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_NCR }}
          username: ${{ secrets.NCP_NCR_ACCESS_KEY }}
          password: ${{ secrets.NCP_NCR_SECRET_KEY }}

      - name: Push Docker image / tag with build number
        run: docker push ${{ secrets.NCP_NCR }}/$IMAGE_NAME:${{ github.run_number }}

      - name: Push Docker image / tag latest
        run: docker push ${{ secrets.NCP_NCR }}/$IMAGE_NAME:latest

      - name: Copy Docker Compose file to NCP Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          source: docker-compose.yml
          target: /deploy/scripts

      - name: Connect ssh to NCP Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          script: |
            cd /deploy/scripts
            echo ${{ secrets.NCP_NCR_SECRET_KEY }} | docker login -u ${{ secrets.NCP_NCR_ACCESS_KEY }} --password-stdin ${{ secrets.NCP_NCR }}
            docker pull ${{ secrets.NCP_NCR }}/$IMAGE_NAME:latest
            if [[ $(docker ps -q) ]]; then
              docker stop $(docker ps -q)
              docker rm $(docker ps -aq)
            else
              echo "No running containers found."
            fi
            docker-compose up -d
            docker logout
