name: Deploy to NCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'bsideproject/KoLiving_FE'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image / tag with build number
        run: docker-compose build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          NCP_NCR: ${{ secrets.NCP_NCR }}
          IMAGE_NAME: koliving_fe

      - name: Build Docker image / tag latest
        run: docker-compose build
        env:
          BUILD_NUMBER: latest
          NCP_NCR: ${{ secrets.NCP_NCR }}
          IMAGE_NAME: koliving_fe

      - name: List Docker images
        run: docker images

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_NCR }}
          username: ${{ secrets.NCP_NCR_ACCESS_KEY }}
          password: ${{ secrets.NCP_NCR_SECRET_KEY }}

      - name: Push Docker image / tag with build number
        run: docker push ${{ secrets.NCP_NCR }}/koliving_fe:${{ secrets.NCP_NCR }}

      - name: Push Docker image / tag latest
        run: docker push ${{ secrets.NCP_NCR }}/koliving_fe:latest

      - name: Connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_IP }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          script: |
            echo ${{ secrets.NCP_NCR_SECRET_KEY }} | docker login -u ${{ secrets.NCP_NCR_ACCESS_KEY }} --password-stdin ${{ secrets.NCP_NCR }}
            docker pull ${{ secrets.NCP_NCR }}/nextjs-docker:latest
            if [[ $(docker ps -q) ]]; then
              docker stop $(docker ps -q)
              docker rm $(docker ps -aq)
            else
              echo "No running containers found."
            fi
            docker run -d -p 80:3000 --name nextjs-docker ${{ secrets.NCP_NCR }}/nextjs-docker:latest
            docker image prune -f
            docker logout
